# Generated by Django 3.2.9 on 2022-06-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220629_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='paidnuntil',
            new_name='paiduntil',
        ),
    ]
