# Generated by Django 3.2.9 on 2022-06-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_paidnuntil_userprofile_paiduntil'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
