# Generated by Django 3.2.9 on 2022-06-27 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('le504', '0002_levelstring'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
